"""
Searcharr settings — auto-generated by setup.ps1 / setup.sh.

Do not edit by hand unless you know what you're doing. If you re-run the
setup script with --telegram (or -Telegram), this file is rewritten using
the API keys it extracts from Sonarr/Radarr.

Placeholders that the setup script substitutes:
  __SEARCHARR_PASSWORD__       random or value of TELEGRAM_BOT_PASSWORD
  __SEARCHARR_ADMIN_PASSWORD__ random or value of TELEGRAM_ADMIN_PASSWORD
  __TGRAM_TOKEN__              value of TELEGRAM_BOT_TOKEN
  __SONARR_API_KEY__           extracted from sonarr config.xml
  __RADARR_API_KEY__           extracted from radarr config.xml
"""

# Searcharr Bot
searcharr_password = "__SEARCHARR_PASSWORD__"
searcharr_admin_password = "__SEARCHARR_ADMIN_PASSWORD__"
searcharr_language = "en-us"
searcharr_start_command_aliases = ["start"]
searcharr_help_command_aliases = ["help"]
searcharr_users_command_aliases = ["users"]

# Telegram
tgram_token = "__TGRAM_TOKEN__"

# Sonarr — reached by Docker service name on the Compose network.
sonarr_enabled = True
sonarr_url = "http://sonarr:8989"
sonarr_api_key = "__SONARR_API_KEY__"
sonarr_quality_profile_id = ["HD-1080p"]
sonarr_add_monitored = True
sonarr_search_on_add = True
sonarr_tag_with_username = True
sonarr_forced_tags = ["telegram"]
sonarr_allow_user_to_select_tags = False
sonarr_user_selectable_tags = []
sonarr_series_command_aliases = ["series", "tv", "show"]
sonarr_series_paths = []
sonarr_season_monitor_prompt = False

# Radarr — reached by Docker service name on the Compose network.
radarr_enabled = True
radarr_url = "http://radarr:7878"
radarr_api_key = "__RADARR_API_KEY__"
radarr_quality_profile_id = ["HD-1080p"]
radarr_add_monitored = True
radarr_search_on_add = True
radarr_tag_with_username = True
radarr_forced_tags = ["telegram"]
radarr_allow_user_to_select_tags = False
radarr_user_selectable_tags = []
radarr_min_availability = "released"
radarr_movie_command_aliases = ["movie", "mv", "m"]
radarr_movie_paths = []
