#!/usr/bin/env bash
# -----------------------------------------------------------------------------
# One-shot installer for the home media server stack on Linux / macOS.
# (Equivalent of setup.ps1.)
#
# Usage: ./setup.sh [--vpn]
# -----------------------------------------------------------------------------
set -euo pipefail

USE_VPN=0
for arg in "$@"; do
    case "$arg" in
        --vpn) USE_VPN=1 ;;
        -h|--help)
            echo "Usage: $0 [--vpn]"
            echo "  --vpn   Route qBittorrent through Gluetun (fill VPN_* in .env first)"
            exit 0 ;;
    esac
done

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

cyan()   { printf "\033[1;36m==> %s\033[0m\n" "$*"; }
green()  { printf "\033[1;32m    %s\033[0m\n" "$*"; }
yellow() { printf "\033[1;33m    %s\033[0m\n" "$*"; }
red()    { printf "\033[1;31m    %s\033[0m\n" "$*"; }

# 1. Docker check ------------------------------------------------------------
cyan "Checking Docker"
if ! command -v docker >/dev/null 2>&1; then
    red "Docker is not installed."
    echo "    macOS:  https://www.docker.com/products/docker-desktop/"
    echo "    Linux:  https://docs.docker.com/engine/install/"
    exit 1
fi
if ! docker info >/dev/null 2>&1; then
    red "Docker daemon is not running. Start Docker Desktop / dockerd and retry."
    exit 1
fi
green "Docker is running."

# 2. Paths -------------------------------------------------------------------
cyan "Resolving paths"
MEDIA_ROOT="${MEDIA_ROOT:-$SCRIPT_DIR/media}"
DOWNLOADS_ROOT="${DOWNLOADS_ROOT:-$SCRIPT_DIR/downloads}"
CONFIG_ROOT="${CONFIG_ROOT:-$SCRIPT_DIR/config}"
TZ_VALUE="${TZ:-$(readlink /etc/localtime 2>/dev/null | sed 's|.*/zoneinfo/||' || echo UTC)}"

mkdir -p "$MEDIA_ROOT"/{movies,tv}
mkdir -p "$DOWNLOADS_ROOT"/{complete,incomplete}
mkdir -p "$CONFIG_ROOT"/{jackett,qbittorrent,sonarr,radarr,overseerr}

green "Media:     $MEDIA_ROOT"
green "Downloads: $DOWNLOADS_ROOT"
green "Config:    $CONFIG_ROOT"

# 3. .env --------------------------------------------------------------------
cyan "Writing .env"
cat > .env <<EOF
# Generated by setup.sh on $(date -u +'%Y-%m-%dT%H:%M:%SZ')
TZ=$TZ_VALUE
PUID=$(id -u)
PGID=$(id -g)
CONFIG_ROOT=$CONFIG_ROOT
DOWNLOADS_ROOT=$DOWNLOADS_ROOT
MEDIA_ROOT=$MEDIA_ROOT
EOF
green ".env written."

# 4. Pull and start ----------------------------------------------------------
COMPOSE=(docker compose)
if [ "$USE_VPN" = "1" ]; then
    COMPOSE+=(-f docker-compose.yml -f docker-compose.vpn.yml)
    cyan "VPN mode enabled (gluetun + qBittorrent)"
    # Append VPN settings template from .env.example if absent.
    if ! grep -q '^VPN_SERVICE_PROVIDER=' .env; then
        awk '/# VPN settings \(optional\)/,/^$/' .env.example >> .env || true
        echo "" >> .env
    fi
    if ! grep -qE '^VPN_SERVICE_PROVIDER=\S' .env; then
        red "VPN_SERVICE_PROVIDER is empty in .env."
        echo "    Edit .env and fill in your provider credentials, then re-run:"
        echo "      ./setup.sh --vpn"
        echo "    See .env.example for Mullvad / ProtonVPN / NordVPN examples."
        exit 1
    fi
fi

cyan "Pulling images (first run can take a few minutes)"
"${COMPOSE[@]}" pull
cyan "Starting containers"
"${COMPOSE[@]}" up -d

# 5. Wait for services -------------------------------------------------------
wait_for_url() {
    local name="$1" url="$2" deadline=$(( $(date +%s) + 90 ))
    while [ "$(date +%s)" -lt "$deadline" ]; do
        if curl -fsS --max-time 3 -o /dev/null -w '%{http_code}' "$url" 2>/dev/null \
            | grep -qE '^[1-4][0-9][0-9]$'; then
            green "$name ready at $url"; return 0
        fi
        sleep 1
    done
    yellow "$name did not respond within timeout (may still be initialising)."
    return 1
}

cyan "Waiting for services to come up"
wait_for_url "Jackett"     "http://localhost:9117" || true
wait_for_url "qBittorrent" "http://localhost:8080" || true
wait_for_url "Sonarr"      "http://localhost:8989" || true
wait_for_url "Radarr"      "http://localhost:7878" || true
wait_for_url "Overseerr"   "http://localhost:5055" || true

# 6. Extract credentials & API keys -----------------------------------------
sleep 5
qbt_pass="$(docker logs qbittorrent 2>&1 | grep -oE 'temporary password[^:]*:[[:space:]]*[^[:space:]]+' \
    | tail -n1 | awk -F: '{print $NF}' | tr -d ' ')"

extract_arr_key() {
    local file="$1"
    [ -f "$file" ] || return 0
    grep -oE '<ApiKey>[^<]+</ApiKey>' "$file" | head -n1 | sed -E 's|</?ApiKey>||g'
}
extract_jackett_key() {
    local file="$1"
    [ -f "$file" ] || return 0
    grep -oE '"APIKey"[^,]*' "$file" | head -n1 | sed 's/.*"APIKey":[[:space:]]*"\([^"]*\)".*/\1/'
}

sonarr_key="$(extract_arr_key  "$CONFIG_ROOT/sonarr/config.xml")"
radarr_key="$(extract_arr_key  "$CONFIG_ROOT/radarr/config.xml")"
jackett_key="$(extract_jackett_key "$CONFIG_ROOT/jackett/Jackett/ServerConfig.json")"

# 7. Summary -----------------------------------------------------------------
cat <<EOF

============================================================
 Media server is up. Open these in your browser:
============================================================

  Jackett      http://localhost:9117
  qBittorrent  http://localhost:8080
  Sonarr       http://localhost:8989
  Radarr       http://localhost:7878
  Overseerr    http://localhost:5055

Credentials & API keys
----------------------
EOF
if [ -n "$qbt_pass" ]; then
    echo "  qBittorrent  user: admin"
    echo "  qBittorrent  pass: $qbt_pass   <-- change this on first login!"
else
    yellow "Could not find qBittorrent temp password. Run:"
    echo   "      docker logs qbittorrent | grep -i 'temporary password'"
fi
[ -n "$jackett_key" ] && echo "  Jackett  API key: $jackett_key"
[ -n "$sonarr_key"  ] && echo "  Sonarr   API key: $sonarr_key"
[ -n "$radarr_key"  ] && echo "  Radarr   API key: $radarr_key"

cat <<'EOF'

Paths inside containers (use these in Sonarr/Radarr/qBittorrent UI):
  qBittorrent complete dir   /downloads/complete
  qBittorrent incomplete dir /downloads/incomplete
  Sonarr TV root folder      /tv
  Radarr Movies root folder  /movies

Next steps: see README.md, section "Wire the services together".

EOF

if [ "$USE_VPN" = "1" ]; then
    yellow "VPN is active. Important wiring difference:"
    echo   "    In Sonarr/Radarr -> Download Clients -> qBittorrent, set the"
    echo   "    Host field to 'gluetun' (NOT 'qbittorrent'). qBit shares the"
    echo   "    gluetun container's network and is only reachable via that name."
    echo   "    Verify your public IP with:"
    echo   "      docker exec gluetun wget -qO- https://ifconfig.me"
    echo   ""
fi
