<#
.SYNOPSIS
    One-shot installer for the home media server stack on Windows.

.DESCRIPTION
    - Verifies Docker Desktop is installed and running.
    - Creates media, downloads, and config folders.
    - Generates .env from .env.example if missing (with Windows-friendly paths).
    - Pulls images and starts the stack with `docker compose up -d`.
    - Waits for qBittorrent to print its first-run password, extracts it, and
      displays it together with all service URLs and API keys.

.PARAMETER MediaRoot
    Folder for your library (movies/ and tv/ are created inside it).
    Example: D:\media

.PARAMETER DownloadsRoot
    Folder for torrent downloads. Example: D:\downloads

.PARAMETER ConfigRoot
    Folder for service configs (state, databases, settings).
    Example: D:\media-server\config

.PARAMETER Vpn
    Route qBittorrent through a Gluetun VPN container. Requires VPN_*
    values to be set in .env (see .env.example for examples).

.EXAMPLE
    .\setup.ps1
    Uses default paths under the current directory.

.EXAMPLE
    .\setup.ps1 -MediaRoot D:\media -DownloadsRoot D:\downloads

.EXAMPLE
    .\setup.ps1 -Vpn
    Same as above but routes qBittorrent through the VPN.
#>

[CmdletBinding()]
param(
    [string]$MediaRoot,
    [string]$DownloadsRoot,
    [string]$ConfigRoot,
    [string]$Timezone,
    [switch]$Vpn
)

$ErrorActionPreference = "Stop"
Set-Location -Path $PSScriptRoot

function Write-Step($msg)    { Write-Host "==> $msg" -ForegroundColor Cyan }
function Write-OK($msg)      { Write-Host "    $msg" -ForegroundColor Green }
function Write-WarnMsg($msg) { Write-Host "    $msg" -ForegroundColor Yellow }
function Write-ErrMsg($msg)  { Write-Host "    $msg" -ForegroundColor Red }

# -----------------------------------------------------------------------------
# 1. Prerequisites
# -----------------------------------------------------------------------------
Write-Step "Checking Docker Desktop"

$dockerCmd = Get-Command docker -ErrorAction SilentlyContinue
if (-not $dockerCmd) {
    Write-ErrMsg "Docker is not installed."
    Write-Host ""
    Write-Host "Install Docker Desktop for Windows, then re-run this script:"
    Write-Host "  https://www.docker.com/products/docker-desktop/"
    Write-Host ""
    Write-Host "Or with winget:  winget install Docker.DockerDesktop"
    exit 1
}

try {
    docker info --format '{{.ServerVersion}}' 2>$null | Out-Null
    if ($LASTEXITCODE -ne 0) { throw "daemon not reachable" }
    Write-OK "Docker is running."
} catch {
    Write-ErrMsg "Docker Desktop is installed but not running."
    Write-Host "    Start Docker Desktop and wait for the whale icon to settle, then re-run."
    exit 1
}

# -----------------------------------------------------------------------------
# 2. Resolve paths
# -----------------------------------------------------------------------------
Write-Step "Resolving paths"

if (-not $MediaRoot)     { $MediaRoot     = Join-Path $PSScriptRoot "media" }
if (-not $DownloadsRoot) { $DownloadsRoot = Join-Path $PSScriptRoot "downloads" }
if (-not $ConfigRoot)    { $ConfigRoot    = Join-Path $PSScriptRoot "config" }
if (-not $Timezone)      { $Timezone      = (Get-TimeZone).Id }

# Docker on Windows accepts forward slashes; normalise for the .env file.
function ConvertTo-DockerPath($p) {
    return ($p -replace '\\', '/')
}

$MediaRootDocker     = ConvertTo-DockerPath (Resolve-Path -LiteralPath (New-Item -ItemType Directory -Force -Path $MediaRoot)).Path
$DownloadsRootDocker = ConvertTo-DockerPath (Resolve-Path -LiteralPath (New-Item -ItemType Directory -Force -Path $DownloadsRoot)).Path
$ConfigRootDocker    = ConvertTo-DockerPath (Resolve-Path -LiteralPath (New-Item -ItemType Directory -Force -Path $ConfigRoot)).Path

Write-OK "Media:     $MediaRootDocker"
Write-OK "Downloads: $DownloadsRootDocker"
Write-OK "Config:    $ConfigRootDocker"

# -----------------------------------------------------------------------------
# 3. Create folder layout
# -----------------------------------------------------------------------------
Write-Step "Creating folder layout"

$folders = @(
    "$MediaRoot\movies",
    "$MediaRoot\tv",
    "$DownloadsRoot\complete",
    "$DownloadsRoot\incomplete",
    "$ConfigRoot\jackett",
    "$ConfigRoot\qbittorrent",
    "$ConfigRoot\sonarr",
    "$ConfigRoot\radarr",
    "$ConfigRoot\overseerr"
)
foreach ($f in $folders) {
    if (-not (Test-Path -LiteralPath $f)) {
        New-Item -ItemType Directory -Force -Path $f | Out-Null
        Write-OK "created $f"
    }
}

# -----------------------------------------------------------------------------
# 4. Generate .env
# -----------------------------------------------------------------------------
Write-Step "Writing .env"

$envPath = Join-Path $PSScriptRoot ".env"
$envBody = @"
# Generated by setup.ps1 on $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')
TZ=$Timezone
PUID=1000
PGID=1000
CONFIG_ROOT=$ConfigRootDocker
DOWNLOADS_ROOT=$DownloadsRootDocker
MEDIA_ROOT=$MediaRootDocker
"@
Set-Content -LiteralPath $envPath -Value $envBody -Encoding UTF8
Write-OK ".env written."

# -----------------------------------------------------------------------------
# 4b. VPN preflight
# -----------------------------------------------------------------------------
$composeArgs = @("compose")
if ($Vpn) {
    $composeArgs += @("-f", "docker-compose.yml", "-f", "docker-compose.vpn.yml")
    Write-Step "VPN mode enabled (gluetun + qBittorrent)"

    $envExample = Get-Content -LiteralPath (Join-Path $PSScriptRoot ".env.example") -Raw
    $vpnBlock   = ($envExample -split "# VPN settings \(optional\)")[1]
    if ($vpnBlock) {
        Add-Content -LiteralPath $envPath -Value "`n# VPN settings (optional)$vpnBlock"
    }

    if (-not $env:VPN_SERVICE_PROVIDER) {
        $envContent = Get-Content -LiteralPath $envPath -Raw
        if ($envContent -notmatch '(?m)^VPN_SERVICE_PROVIDER=\S') {
            Write-WarnMsg "VPN_SERVICE_PROVIDER is empty in .env."
            Write-Host    "    Edit .env and fill in your provider credentials, then re-run:"
            Write-Host    "      .\setup.ps1 -Vpn"
            Write-Host    "    See .env.example for Mullvad / ProtonVPN / NordVPN examples."
            exit 1
        }
    }
}

# -----------------------------------------------------------------------------
# 5. Start the stack
# -----------------------------------------------------------------------------
Write-Step "Pulling images (first run can take a few minutes)"
& docker @composeArgs pull
if ($LASTEXITCODE -ne 0) { Write-ErrMsg "docker compose pull failed."; exit 1 }

Write-Step "Starting containers"
& docker @composeArgs up -d
if ($LASTEXITCODE -ne 0) { Write-ErrMsg "docker compose up failed."; exit 1 }

# -----------------------------------------------------------------------------
# 6. Wait for services to be reachable
# -----------------------------------------------------------------------------
function Wait-ForUrl($name, $url, $timeoutSec = 90) {
    $deadline = (Get-Date).AddSeconds($timeoutSec)
    while ((Get-Date) -lt $deadline) {
        try {
            $r = Invoke-WebRequest -Uri $url -UseBasicParsing -TimeoutSec 3 -MaximumRedirection 5
            if ($r.StatusCode -lt 500) { return $true }
        } catch { Start-Sleep -Milliseconds 750 }
    }
    return $false
}

Write-Step "Waiting for services to come up"
$services = @(
    @{ name = "Jackett";     url = "http://localhost:9117" },
    @{ name = "qBittorrent"; url = "http://localhost:8080" },
    @{ name = "Sonarr";      url = "http://localhost:8989" },
    @{ name = "Radarr";      url = "http://localhost:7878" },
    @{ name = "Overseerr";   url = "http://localhost:5055" }
)
foreach ($s in $services) {
    if (Wait-ForUrl $s.name $s.url) {
        Write-OK "$($s.name) ready at $($s.url)"
    } else {
        Write-WarnMsg "$($s.name) did not respond within timeout (it may still be initialising)."
    }
}

# -----------------------------------------------------------------------------
# 7. Retrieve qBittorrent temp password and API keys
# -----------------------------------------------------------------------------
function Get-QbtTempPassword {
    $logs = docker logs qbittorrent 2>&1 | Out-String
    $m = [regex]::Match($logs, "temporary password.*?:\s*([^\s]+)")
    if ($m.Success) { return $m.Groups[1].Value }
    return $null
}

function Get-ArrApiKey($configFile) {
    if (-not (Test-Path -LiteralPath $configFile)) { return $null }
    try {
        [xml]$cfg = Get-Content -LiteralPath $configFile -Raw
        return $cfg.Config.ApiKey
    } catch { return $null }
}

function Get-JackettApiKey($configFile) {
    if (-not (Test-Path -LiteralPath $configFile)) { return $null }
    try {
        $j = Get-Content -LiteralPath $configFile -Raw | ConvertFrom-Json
        return $j.APIKey
    } catch { return $null }
}

# Give Sonarr/Radarr/Jackett a few extra seconds to write their config files.
Start-Sleep -Seconds 5

$qbtPass     = Get-QbtTempPassword
$sonarrKey   = Get-ArrApiKey  (Join-Path $ConfigRoot "sonarr\config.xml")
$radarrKey   = Get-ArrApiKey  (Join-Path $ConfigRoot "radarr\config.xml")
$jackettKey  = Get-JackettApiKey (Join-Path $ConfigRoot "jackett\Jackett\ServerConfig.json")

# -----------------------------------------------------------------------------
# 8. Summary
# -----------------------------------------------------------------------------
Write-Host ""
Write-Host "============================================================" -ForegroundColor Magenta
Write-Host " Media server is up. Open these in your browser:" -ForegroundColor Magenta
Write-Host "============================================================" -ForegroundColor Magenta
Write-Host ""
Write-Host "  Jackett      http://localhost:9117"
Write-Host "  qBittorrent  http://localhost:8080"
Write-Host "  Sonarr       http://localhost:8989"
Write-Host "  Radarr       http://localhost:7878"
Write-Host "  Overseerr    http://localhost:5055"
Write-Host ""

Write-Host "Credentials & API keys" -ForegroundColor Magenta
Write-Host "----------------------"
if ($qbtPass) {
    Write-Host "  qBittorrent  user: admin"
    Write-Host "  qBittorrent  pass: $qbtPass   <-- change this on first login!"
} else {
    Write-WarnMsg "Could not find qBittorrent temp password. Run:"
    Write-Host    "      docker logs qbittorrent | findstr /i ""temporary password"""
}
if ($jackettKey) { Write-Host "  Jackett  API key: $jackettKey" }
if ($sonarrKey)  { Write-Host "  Sonarr   API key: $sonarrKey" }
if ($radarrKey)  { Write-Host "  Radarr   API key: $radarrKey" }
Write-Host ""

Write-Host "Paths inside containers (use these in Sonarr/Radarr/qBittorrent UI):" -ForegroundColor Magenta
Write-Host "  qBittorrent complete dir   /downloads/complete"
Write-Host "  qBittorrent incomplete dir /downloads/incomplete"
Write-Host "  Sonarr TV root folder      /tv"
Write-Host "  Radarr Movies root folder  /movies"
if ($Vpn) {
    Write-Host ""
    Write-Host "VPN is active. Important wiring difference:" -ForegroundColor Yellow
    Write-Host "  In Sonarr/Radarr -> Download Clients -> qBittorrent, set the"
    Write-Host "  Host field to 'gluetun' (NOT 'qbittorrent'). qBit shares the"
    Write-Host "  gluetun container's network and is only reachable via that name."
    Write-Host "  Check your public IP with:  docker exec gluetun wget -qO- https://ifconfig.me"
}
Write-Host ""
Write-Host "Next steps: see README.md, section 'Wire the services together'." -ForegroundColor Magenta
Write-Host ""
